    - name: Kernel Configure
      run: |
        ./build config           
                model=G9730      
                name="MK-NETHUNTER10"
                +magisk          
                +nohardening     
                +ttl             
                +wireguard       
                +cifs            
                +sdfat           
                +ntfs            
                +tcp_cibuc       
                +morosound       
                +boeffla_wl_blocker
